site_name: flowMC
site_description: Normalizing-flow enhanced sampling package for probabilistic inference in JAX
site_author: GW JAX Team
repo_url: https://github.com/GW-JAX-Team/flowMC
repo_name: GW-JAX-Team/flowMC

theme:
    name: material
    features:
        - navigation
        - toc
        - header.autohide
    palette:
        - scheme: default
          primary: cyan
          accent: deep purple
          toggle:
             icon: material/brightness-5
             name: Dark mode
        - scheme: slate
          primary: custom
          accent: purple
          toggle:
             icon: material/brightness-2
             name: Light mode

markdown_extensions:
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.superfences
    - pymdownx.details
    - pymdownx.snippets:
        base_path: docs
    - admonition
    - toc:
        permalink: "¤"
        toc_depth: 4

plugins:
    - search
    - autorefs
    - mkdocs-jupyter:
    - gen-files:
        scripts:
        - docs/gen_ref_pages.py
    - literate-nav:
        nav_file: SUMMARY.md
    - mkdocstrings:
        handlers:
            python:
                options:
                    docstring_style: google
                    inherited_members: true
                    show_root_heading: true
                    show_root_full_path: true
                    show_if_no_docstring: true
                    show_signature_annotations: true
                    show_source: false
                    members_order: source
                    heading_level: 4

extra_css:
  - stylesheets/extra.css

nav:
    - Home: index.md
    - Getting Started: quickstart.md
    - Configuration: configuration.md
    - Tutorials:
        - Step-by-step guide: tutorials/dualmoon.ipynb
        - Custom Strategy: tutorials/custom_strategy.ipynb
        - Training Normalizing Flow: tutorials/train_normalizing_flow.ipynb
        - Loading Resource: tutorials/loading_resources.ipynb
    - Community Examples: communityExamples.md
    - FAQ: FAQ.md
    - Contributing: contributing.md
    - Changelog: changelog.md
    - API: api/flowMC/*
