site_name: flowMC
site_description: A JAX-based normalizing-flow-enhanced MCMC sampler for probabilistic inference
site_author: GW JAX Team
repo_url: https://github.com/GW-JAX-Team/flowMC
repo_name: GW-JAX-Team/flowMC

theme:
    name: material
    features:
        - navigation
        - toc
        - header.autohide
    palette:
        - scheme: slate
          primary: black
          accent: amber
          toggle:
             icon: material/brightness-5
             name: Light mode
        - scheme: default
          primary: blue
          accent: deep purple
          toggle:
             icon: material/brightness-2
             name: Dark mode

markdown_extensions:
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.superfences
    - pymdownx.details
    - pymdownx.snippets:
        base_path: docs
    - admonition
    - toc:
        permalink: "¤"
        toc_depth: 4

plugins:
    - search
    - autorefs
    - mkdocs-jupyter:
        include: ["*.ipynb"]
    - gen-files:
        scripts:
        - docs/gen_ref_pages.py
    - literate-nav:
        nav_file: SUMMARY.md
    - mkdocstrings:
        handlers:
            python:
                options:
                    docstring_style: google
                    inherited_members: true
                    show_root_heading: true
                    show_root_full_path: true
                    show_if_no_docstring: true
                    show_signature_annotations: true
                    show_source: false
                    members_order: source
                    heading_level: 4

nav:
    - Home: index.md
    - Installation: installation.md
    - Quick Start: quickstart.md
    - Tutorials:
        - Overview: tutorials/index.md
        - Step-by-Step Example: tutorials/dualmoon.ipynb
        - Parallel Tempering: tutorials/parallel_tempering.ipynb
        - Custom Strategy Composition: tutorials/custom_strategy.ipynb
        - Training Normalizing Flows: tutorials/train_normalizing_flow.ipynb
        - Training Flow Matching Models: tutorials/train_flow_match.ipynb
    - Hyperparameter Reference: hyperparameter_reference.md
    - FAQ: FAQ.md
    - Contributing: contributing.md
    - Development Guide: development_guide.md
    - API: api/flowMC/*
